version: '{build}'

os: 
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
  - additional_flags: ""
    generator: "Visual Studio 14 2015"
  - additional_flags: ""
    generator: "Visual Studio 15 2017"
  - additional_flags: "/permissive- /std:c++latest /utf-8"
    generator: "Visual Studio 15 2017"
  - additional_flags: ""
    generator: "MinGW Makefiles"

matrix:
  exclude:
    - additional_flags: "/permissive- /std:c++latest /utf-8"
      os: Visual Studio 2015
    - generator: "Visual Studio 15 2017"
      os: Visual Studio 2015
    - generator: "Visual Studio 14 2015"
      os: Visual Studio 2017

init: []

install: []

build_script:
  - cmake . -G"%generator%" -DCMAKE_CXX_FLAGS="%additional_flags%"
  - cmake --build . --config Release

test_script:
  - ctest -C Release -V
